import streamlit as st
import requests

API_URL = "http://127.0.0.1:8000/predict"

import os
from PIL import Image
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from io import BytesIO
from datetime import datetime

# ============================================================
# PDF REPORT GENERATOR
# ============================================================

def create_prediction_pdf(
    Gender,
    Married,
    Dependents,
    Education,
    Self_Employed,
    ApplicantIncome,
    CoapplicantIncome,
    LoanAmount,
    Loan_Amount_Term,
    Credit_History,
    Property_Area,
    approved,
    probability,
    confidence
):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    heading_style = styles["Heading2"]

    normal_style = styles["BodyText"]

    story = []

    # ---------------- Title ----------------

    story.append(
        Paragraph(
            "Loan Eligibility Prediction Report",
            title_style
        )
    )

    story.append(Spacer(1, 20))

    # ---------------- Date ----------------

    prediction_date = datetime.now().strftime(
        "%d-%m-%Y %I:%M %p"
    )

    story.append(
        Paragraph(
            f"<b>Prediction Date:</b> {prediction_date}",
            normal_style
        )
    )

    story.append(Spacer(1, 15))

    # ---------------- Prediction Result ----------------

    story.append(
        Paragraph(
            "Prediction Result",
            heading_style
        )
    )

    result_text = "LOAN APPROVED" if approved else "LOAN NOT APPROVED"

    story.append(
        Paragraph(
            f"<b>Decision:</b> {result_text}",
            normal_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Approval Probability:</b> {probability * 100:.1f}%",
            normal_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Confidence:</b> {confidence}",
            normal_style
        )
    )

    story.append(Spacer(1, 20))

    # ---------------- Applicant Details ----------------

    story.append(
        Paragraph(
            "Applicant Details",
            heading_style
        )
    )

    data = [
        ["Field", "Value"],
        ["Gender", Gender],
        ["Married", Married],
        ["Dependents", Dependents],
        ["Education", Education],
        ["Self Employed", Self_Employed],
        ["Applicant Income", f"{ApplicantIncome:.2f}"],
        ["Co-applicant Income", f"{CoapplicantIncome:.2f}"],
        ["Loan Amount", f"{LoanAmount:.2f}"],
        ["Loan Term", f"{Loan_Amount_Term:.0f} months"],
        ["Credit History", str(Credit_History)],
        ["Property Area", Property_Area],
    ]

    table = Table(
        data,
        colWidths=[200, 300]
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#4F6EF7")
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.white
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold"
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.grey
                ),
                (
                    "BACKGROUND",
                    (0, 1),
                    (-1, -1),
                    colors.whitesmoke
                ),
                (
                    "PADDING",
                    (0, 0),
                    (-1, -1),
                    8
                ),
            ]
        )
    )

    story.append(table)

    story.append(Spacer(1, 25))

    # ---------------- Footer ----------------

    story.append(
        Paragraph(
            "Generated by Loan Eligibility Predictor",
            normal_style
        )
    )

    doc.build(story)

    buffer.seek(0)

    return buffer

# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="Loan Eligibility Predictor",
    page_icon="🏛️",
    layout="centered"
)

# ============================================================
# THEME MODE
# ============================================================

# Streamlit Settings controls the active theme.
effective_dark_mode = False

# ============================================================
# PREDICTION HISTORY
# ============================================================

if "prediction_history" not in st.session_state:
    st.session_state.prediction_history = []

# ============================================================
# RESPONSIVE GLASS UI CSS
# ============================================================

st.markdown(
    """
    <style>

    /* ---------------- Page Background ---------------- */

    .stApp {
    background: var(--background-color);
    color: var(--text-color);
    background-attachment: fixed;
}

    /* ---------------- Top Glow ---------------- */

    @keyframes glow {

        0% {
            box-shadow:
                0 -2px 30px rgba(76, 110, 245, .25) inset;
        }

        50% {
            box-shadow:
                0 -2px 45px rgba(76, 110, 245, .45) inset;
        }

        100% {
            box-shadow:
                0 -2px 30px rgba(76, 110, 245, .25) inset;
        }

    }


    .block-container {
        padding-top: 2.2rem;
        animation: glow 6s ease-in-out infinite;
    }


    /* ---------------- Glass Card ---------------- */

    .glass {
        background: rgba(255, 255, 255, .55);

        border-radius: 18px;

        border: 1px solid rgba(255, 255, 255, .35);

        box-shadow:
            0 10px 30px rgba(16, 24, 40, .08),
            0 1px 0 rgba(255, 255, 255, .6) inset;

        backdrop-filter: blur(10px);
        -webkit-backdrop-filter: blur(10px);

        padding: 22px 22px 8px 22px;
    }


    /* ---------------- Title ---------------- */

    h1.glass-title {

        text-align: center;

        margin: 0 0 6px 0;

        color: var(--text-color) !important;

        letter-spacing: .3px;

        font-size: 2rem;
    }


    .subtitle {

        text-align: center;

        color: var(--text-color) !important;

        margin: -2px 0 18px 0;

        font-size: .95rem;
    }


    /* ---------------- Inputs ---------------- */

    .stSelectbox > div,
    .stNumberInput > div,
    .stTextInput > div {

        background: rgba(255, 255, 255, .65);

        border: 1px solid rgba(15, 23, 42, .07);

        border-radius: 12px;
    }


    .stSelectbox:hover > div,
    .stNumberInput:hover > div,
    .stTextInput:hover > div {

        border-color: rgba(76, 110, 245, .35);
    }


    /* ---------------- Buttons ---------------- */

    .stButton > button {

        background: linear-gradient(
            135deg,
            #4c6ef5 0%,
            #7c8dfb 100%
        );

        border: 0;

        color: white;

        border-radius: 12px;

        padding: .6rem 1.1rem;

        font-weight: 600;

        box-shadow:
            0 10px 18px rgba(76, 110, 245, .25);

        width: 100%;
    }


    .stButton > button:hover {

        filter: brightness(1.05);

        box-shadow:
            0 12px 20px rgba(76, 110, 245, .32);
    }


    /* ---------------- Result Cards ---------------- */

    .result-card {

        padding: 25px;

        border-radius: 15px;

        margin-top: 15px;

        margin-bottom: 15px;
    }


    /* ---------------- Footer ---------------- */

    .footer-note {

        color: #6b7280;

        text-align: center;

        font-size: .85rem;

        margin-top: 8px;
    }


    /* ========================================================
       MOBILE RESPONSIVE DESIGN
       ======================================================== */

    @media (max-width: 768px) {

        /* Reduce page spacing */

        .block-container {

            padding-left: 1rem;
            padding-right: 1rem;
            padding-top: 1rem;
        }


        /* Smaller title */

        h1.glass-title {

            font-size: 1.55rem;
        }


        .subtitle {

            font-size: .85rem;

            margin-bottom: 15px;
        }


        /* Stack columns vertically */

        [data-testid="stHorizontalBlock"] {

            flex-direction: column !important;

            gap: 0.5rem !important;
        }


        [data-testid="column"] {

            width: 100% !important;

            flex: 1 1 100% !important;
        }


        /* Make buttons full width */

        .stButton > button {

            width: 100%;

            min-height: 45px;

            font-size: 1rem;
        }


        /* Result card */

        .result-card {

            padding: 18px;

            border-radius: 14px;
        }


        .result-card h2 {

            font-size: 1.35rem;
        }


        .result-card div {

            font-size: 17px !important;
        }


        /* SHAP images */

        img {

            max-width: 100% !important;

            height: auto !important;
        }

    }


    /* ========================================================
       SMALL PHONE RESPONSIVE DESIGN
       ======================================================== */

    @media (max-width: 480px) {

        .block-container {

            padding-left: .7rem;
            padding-right: .7rem;
        }


        h1.glass-title {

            font-size: 1.35rem;
        }


        .subtitle {

            font-size: .78rem;
        }


        .glass {

            padding: 15px 12px 8px 12px;

            border-radius: 14px;
        }


        .stButton > button {

            min-height: 48px;

            font-size: .95rem;
        }


        .result-card {

            padding: 15px;
        }


        .result-card h2 {

            font-size: 1.2rem;
        }

    }

    </style>
    """,
    unsafe_allow_html=True
)

# ============================================================
# DARK MODE VISIBILITY
# ============================================================

if effective_dark_mode:
    
    st.markdown(
        """
        <style>

        /* =========================
           APP BACKGROUND
           ========================= */

        .stApp {
            background: #0f172a !important;
            color: #f8fafc !important;
        }

        /* =========================
           MAIN GLASS CARD
           ========================= */

        .glass {
            background: rgba(15, 23, 42, 0.72) !important;
            border: 1px solid rgba(148, 163, 184, 0.20) !important;
            box-shadow:
                0 10px 30px rgba(0, 0, 0, 0.25),
                0 1px 0 rgba(255, 255, 255, 0.06) inset !important;
        }

        /* =========================
           HEADINGS
           ========================= */

        .stApp h1,
        .stApp h2,
        .stApp h3,
        .stApp h4,
        .stApp h5,
        .stApp h6 {
            color: #f8fafc !important;
        }

        h1.glass-title {
            color: #f8fafc !important;
        }

        .subtitle {
            color: #cbd5e1 !important;
        }

        /* =========================
           WIDGET LABELS
           ========================= */

        div[data-testid="stWidgetLabel"] label,
        div[data-testid="stWidgetLabel"] p,
        div[data-testid="stWidgetLabel"] * {
            color: #f8fafc !important;
        }

        /* =========================
           SELECTBOX
           ========================= */

        div[data-baseweb="select"] {
            color: #f8fafc !important;
        }

        div[data-baseweb="select"] > div {
            background-color: #1e293b !important;
            border-color: #475569 !important;
        }

        div[data-baseweb="select"] * {
            color: #f8fafc !important;
        }

        div[data-baseweb="select"] svg {
            fill: #f8fafc !important;
        }

        /* =========================
           NUMBER INPUT
           ========================= */

        div[data-baseweb="input"] {
            color: #f8fafc !important;
        }

        div[data-baseweb="input"] > div {
            background-color: #1e293b !important;
            border-color: #475569 !important;
        }

        div[data-baseweb="input"] input {
            background-color: #1e293b !important;
            color: #f8fafc !important;
            caret-color: #f8fafc !important;
        }

        div[data-testid="stNumberInput"] button {
            color: #f8fafc !important;
        }

        /* =========================
           BUTTONS
           ========================= */

        .stButton > button {
            color: #ffffff !important;

            background: linear-gradient(
                135deg,
                #4f46e5,
                #6366f1
            ) !important;

            border: none !important;
        }

        /* =========================
           DOWNLOAD BUTTON
           ========================= */

        .stDownloadButton > button {
            background: #1e293b !important;
            color: #f8fafc !important;
            border: 1px solid #475569 !important;
        }

        /* =========================
           MARKDOWN / TEXT
           ========================= */

        .stMarkdown,
        .stMarkdown p,
        .stMarkdown strong {
            color: #f8fafc !important;
        }

        /* =========================
           DIVIDERS
           ========================= */

        hr {
            border-color: #475569 !important;
        }

        /* =========================
           PREDICTION HISTORY
           ========================= */

        [data-testid="stDataFrame"] {
            background: #0f172a !important;
        }

        /* =========================
           INFO / WARNING / SUCCESS
           ========================= */

        [data-testid="stAlert"] {
            color: #f8fafc !important;
        }

        /* =========================
           FOOTER
           ========================= */

        .footer-note {
            color: #94a3b8 !important;
        }
        
/* RESULT CARD TEXT */
.loan-result-card,
.loan-result-card h1,
.loan-result-card h2,
.loan-result-card h3,
.loan-result-card h4,
.loan-result-card p,
.loan-result-card strong,
.loan-result-card div {
    color: #172033 !important;
}

        </style>
        """,
        unsafe_allow_html=True
    )
    

# ============================================================
# FINAL DARK MODE UI FIX
# ============================================================

if effective_dark_mode:
    
    st.markdown(
        """
        <style>

        /* ---------------- WIDGET LABELS ---------------- */

        div[data-testid="stWidgetLabel"] label,
        div[data-testid="stWidgetLabel"] p,
        div[data-testid="stWidgetLabel"] span,
        div[data-testid="stWidgetLabel"] * {
            color: #f8fafc !important;
            opacity: 1 !important;
        }


        /* ---------------- SELECTBOX LABELS ---------------- */

        .stSelectbox label,
        .stNumberInput label {
            color: #f8fafc !important;
            opacity: 1 !important;
        }


        /* ---------------- NUMBER INPUT ---------------- */

        div[data-baseweb="input"] {
            background-color: #1e293b !important;
        }

        div[data-baseweb="input"] > div {
            background-color: #1e293b !important;
        }

        div[data-baseweb="input"] input {
            background-color: #1e293b !important;
            color: #f8fafc !important;
        }


        /* ---------------- NUMBER INPUT +/- BUTTONS ---------------- */

        div[data-testid="stNumberInput"] button {
            background-color: #1e293b !important;
            color: #f8fafc !important;
            border: none !important;
        }

        div[data-testid="stNumberInput"] button:hover {
            background-color: #334155 !important;
            color: #ffffff !important;
        }

        div[data-testid="stNumberInput"] button svg {
            fill: #f8fafc !important;
            color: #f8fafc !important;
        }


        /* ---------------- INPUT TEXT ---------------- */

        div[data-baseweb="select"] {
            color: #f8fafc !important;
        }

        div[data-baseweb="select"] span {
            color: #f8fafc !important;
        }


        /* ---------------- HEADINGS ---------------- */

        h1.glass-title {
            color: #f8fafc !important;
        }

        .subtitle {
            color: #cbd5e1 !important;
        }


        /* ---------------- HISTORY / INFO ---------------- */

        [data-testid="stAlert"] {
            color: #f8fafc !important;
        }

        [data-testid="stDataFrame"] {
            color: #f8fafc !important;
        }


/* LOAN APPROVED CARD — DARK MODE */
.loan-result-card h2 {
    color: #34d399 !important;
}

.loan-result-card div {
    color: #f8fafc !important;
}

.loan-result-card strong {
    color: #f8fafc !important;
}
        </style>
        """,
        unsafe_allow_html=True
    )
    
# ============================================================
# HEADER
# ============================================================

st.markdown(
    "<h1 class='glass-title'>🏛️ Loan Eligibility Predictor</h1>",
    unsafe_allow_html=True
)

st.markdown(
    "<div class='subtitle'>Premium glass UI • powered by FastAPI + Streamlit</div>",
    unsafe_allow_html=True
)


# ============================================================
# GLASS CARD
# ============================================================

with st.container():

    st.markdown(
        "<div class='glass'>",
        unsafe_allow_html=True
    )
    
# ============================================================
# RESET FORM DEFAULTS
# ============================================================

def reset_form():
    st.session_state["gender"] = "Male"
    st.session_state["dependents"] = "0"
    st.session_state["self_employed"] = "Yes"
    st.session_state["applicant_income"] = 5000
    st.session_state["loan_amount"] = 150

    st.session_state["married"] = "Yes"
    st.session_state["education"] = "Graduate"
    st.session_state["property_area"] = "Urban"
    st.session_state["coapplicant_income"] = 0
    st.session_state["loan_term"] = 360
    st.session_state["credit_history"] = 1

    # Clear current prediction only
    st.session_state.pop("prediction", None)
    
    
# ========================================================
# INPUTS
# ========================================================

col1, col2 = st.columns(2)
        
# ---------------- LEFT COLUMN ----------------
with col1:

    Gender = st.selectbox(
        "Gender",
        ["Male", "Female"],
        key="gender"
    )

    Dependents = st.selectbox(
        "Dependents",
        ["0", "1", "2", "3+"],
        key="dependents"
    )

    Self_Employed = st.selectbox(
        "Self Employed",
        ["Yes", "No"],
        key="self_employed"
    )

    ApplicantIncome = st.number_input(
        "Applicant Income",
        min_value=0,
        max_value=100000,
        step=100,
        key="applicant_income"
    )

    LoanAmount = st.number_input(
        "Loan Amount",
        min_value=1,
        max_value=1000,
        step=1,
        key="loan_amount"
    )


# ---------------- RIGHT COLUMN ----------------
with col2:

    Married = st.selectbox(
        "Married",
        ["Yes", "No"],
        key="married"
    )

    Education = st.selectbox(
        "Education",
        ["Graduate", "Not Graduate"],
        key="education"
    )

    Property_Area = st.selectbox(
        "Property Area",
        ["Urban", "Rural", "Semiurban"],
        key="property_area"
    )

    CoapplicantIncome = st.number_input(
        "Co-applicant Income",
        min_value=0,
        max_value=100000,
        step=100,
        key="coapplicant_income"
    )

    Loan_Amount_Term = st.selectbox(
        "Loan Term (Months)",
        [12, 36, 60, 84, 120, 180, 240, 300, 360],
        key="loan_term"
   )

# CREDIT HISTORY - FULL WIDTH
Credit_History = st.selectbox(
    "Credit History",
    [1, 0],
    key="credit_history"
)

st.write("")

# BUTTONS - BELOW CREDIT HISTORY
col_predict, col_reset = st.columns(2)

with col_predict:
    predict = st.button(
        "Predict",
        use_container_width=True
    )

with col_reset:
    st.button(
        "Reset",
        use_container_width=True,
        on_click=reset_form
    )


    # ============================================================
    # PREDICTION
    # ============================================================

if predict:

    # ========================================================
    # INPUT VALIDATION
    # ========================================================

    if ApplicantIncome <= 0:
        st.warning("Applicant Income must be greater than 0.")
        st.stop()

    if LoanAmount <= 0:
        st.warning("Loan Amount must be greater than 0.")
        st.stop()

    # ========================================================
    # PAYLOAD
    # ========================================================

    payload = {
        "Gender": Gender,
        "Married": Married,
        "Dependents": Dependents,
        "Education": Education,
        "Self_Employed": Self_Employed,
        "ApplicantIncome": float(ApplicantIncome),
        "CoapplicantIncome": float(CoapplicantIncome),
        "LoanAmount": float(LoanAmount),
        "Loan_Amount_Term": float(Loan_Amount_Term),
        "Credit_History": float(Credit_History),
        "Property_Area": Property_Area
    }

    # ========================================================
    # API REQUEST
    # ========================================================

    try:

        with st.spinner("🔄 Making prediction... Please wait..."):

            response = requests.post(
                API_URL,
                json=payload,
                timeout=20
            )

    # ====================================================
    # CHECK RESPONSE
    # ====================================================

        response.raise_for_status()

        result = response.json()

    # ====================================================
    # GET RESULT
    # ====================================================

        approved = result.get("approved")

        probability = float(
            result.get("probability", 0)
        )

        percentage = probability * 100
        
    # ============================================================
    # SAVE PREDICTION HISTORY
    # ============================================================

        history_item = {
            "Time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "Applicant Income": ApplicantIncome,
            "Co-applicant Income": CoapplicantIncome,
            "Loan Amount": LoanAmount,
            "Loan Term": Loan_Amount_Term,
            "Credit History": Credit_History,
            "Result": "Approved" if approved else "Not Approved",
            "Probability": f"{percentage:.1f}%"
        }

        st.session_state.prediction_history.append(history_item)

    # ====================================================
    # APPROVAL RESULT
    # ====================================================

        if approved:
          st.markdown(
        f"""<div class="loan-result-card" style="padding:25px;border-radius:15px;background:#123c32;border:1px solid #2f8f70;margin-top:15px;margin-bottom:15px;color:#f8fafc;">
<h2 style="color:#4ade80;margin-bottom:10px;">✅ Loan Approved</h2>
<div style="font-size:20px;margin-top:10px;color:#f8fafc;">
<strong>Approval Probability:</strong> {percentage:.1f}%
</div>
</div>""",
        unsafe_allow_html=True
    )

        else:

            st.markdown(
                f"""<div class="loan-result-card" style="padding:25px;border-radius:15px;background:#fff0f0;border:1px solid #f5b5b5;margin-top:15px;margin-bottom:15px;">
<h2 style="color:#c62828;margin-bottom:10px;">❌ Loan Not Approved</h2>
<div style="font-size:20px;margin-top:10px;color:#1C273C;"><strong>Approval Probability:</strong> {percentage:.1f}%</div>
</div>""",
                unsafe_allow_html=True
            )

    # ====================================================
    # PROBABILITY
    # ====================================================

        st.write(
            f"### Approval Probability: {percentage:.1f}%"
        )

        st.progress(
            min(
                max(probability, 0.0),
                1.0
            )
        )

    # ====================================================
    # CONFIDENCE
    # ====================================================

        if percentage >= 80:

            confidence = "Very High"

            st.success(
                "🟢 Confidence: Very High"
            )

        elif percentage >= 60:

            confidence = "High"

            st.success(
                "🟢 Confidence: High"
            )

        elif percentage >= 40:

            confidence = "Medium"

            st.warning(
                "🟡 Confidence: Medium"
            )

        else:

            confidence = "Low"

            st.error(
                "🔴 Confidence: Low"
            )

    # ====================================================
    # PDF REPORT
    # ====================================================

        pdf_file = create_prediction_pdf(
            Gender,
            Married,
            Dependents,
            Education,
            Self_Employed,
            ApplicantIncome,
            CoapplicantIncome,
            LoanAmount,
            Loan_Amount_Term,
            Credit_History,
            Property_Area,
            approved,
            probability,
            confidence
        )

    # ====================================================
    # DOWNLOAD PDF
    # ====================================================

        st.download_button(
            label="📄 Download Prediction Report",
            data=pdf_file,
            file_name="loan_prediction_report.pdf",
            mime="application/pdf"
        )

    # ========================================================
    # API ERRORS
    # ========================================================

    except requests.exceptions.ConnectionError:

        st.error(
            "🔌 API Connection Error\n\n"
            "The FastAPI server is not running.\n\n"
            "Please start FastAPI and try again."
        )

    except requests.exceptions.Timeout:

        st.error(
            "⏳ API Timeout\n\n"
            "The prediction service took too long to respond.\n\n"
            "Please try again."
        )

    except requests.exceptions.HTTPError as e:

        st.error(
            f"⚠️ API Error\n\n"
            f"The API returned an HTTP error:\n\n"
            f"{e}"
        )

    except Exception as e:

        st.error(
            f"❌ Unexpected Error\n\n"
            f"Something went wrong while making the prediction.\n\n"
            f"Details: {e}"
        )


# ============================================================
# PREDICTION HISTORY
# ============================================================

st.markdown("---")

st.subheader("📋 Prediction History")

if st.session_state.prediction_history:
    st.dataframe(
        st.session_state.prediction_history,
        width="stretch",
        hide_index=True,
        column_config={
            "Time": st.column_config.TextColumn(
                "Time",
                width="medium"
            ),
            "Applicant Income": st.column_config.NumberColumn(
                "Applicant Income",
                format="₹ %.0f"
            ),
            "Co-applicant Income": st.column_config.NumberColumn(
                "Co-applicant Income",
                format="₹ %.0f"
            ),
            "Loan Amount": st.column_config.NumberColumn(
                "Loan Amount",
                format="₹ %.0f"
            ),
            "Loan Term": st.column_config.NumberColumn(
                "Loan Term",
                format="%.0f months"
            ),
            "Credit History": st.column_config.NumberColumn(
                "Credit History",
                format="%.0f"
            ),
            "Result": st.column_config.TextColumn(
                "Result",
                width="medium"
            ),
            "Probability": st.column_config.TextColumn(
                "Probability",
                width="small"
            )
        },
        height=180
    )
else:
    st.info(
        "No predictions yet. Make a prediction to see it here."
    )
    
    
    
# ============================================================
# SHAP MODEL EXPLAINABILITY
# ============================================================

st.markdown("---")

st.subheader(
    "Model Explainability (SHAP)"
)


summary_path = "reports/shap_summary.png"

bar_path = "reports/shap_bar.png"


if os.path.exists(summary_path):

    st.image(
        summary_path,
        caption="SHAP Summary Plot"
    )


if os.path.exists(bar_path):

    st.image(
        bar_path,
        caption="SHAP Feature Importance"
    )

# ============================================================
# FOOTER
# ============================================================

st.markdown(
    """
    <div class="footer-note">
        Made with ❤️ • Glass UI theme
    </div>
    """,
    unsafe_allow_html=True
)